### ISSUE TITLE
Mouse hover/position behaviour broken in 0.5.6

### ISSUE THREAD

**Issue by screamish** [dorianj/CoRD#15]
Mouse hover behaviour that seems to work brilliantly in 0.5.5 is broken in 0.5.6.

Most simple steps to recreate is trying to trigger anything in a browser that relies on mouseover or hover.

I hope this isn't a dupe, I checked the trac issues too and couldn't find it there.

**Comment by jimbatamang** [comment]
Sorry to say that this issue still exists in OSX in full screen mode while running Windows 7.
