### ISSUE TITLE
OSX 10.10 Yosemite Support

### ISSUE THREAD

**Issue by ryanchantler** [dorianj/CoRD#70]
It appears that OS X 10.10 Yosemite has broken Cord.   :(   I can no longer connect to any remote RDP server via VPN or direct.

**Comment by vikaspushkar** [comment]
the official page says CoRD is supported on 10.5-10.8.... and i am not able to connect to 2012 server even if i use IP addresses i tried to connect to XP machine also ( had one in my storeroom :D ).... is there any thing i am missing?... Is it officially supported on 10.9 and 10.10

**Comment by peelman** [comment]
Don't trust web pages that haven't been updated in years.  That said, CoRD runs on 10.9 and 10.10 (and insofar as I have tested, 10.11).  However as Microsoft has evolved RDP significantly, and CoRD has not kept pace.  That said, 2012 connections are possible, but there are a few glitches and you have to enable the "accept connections from older clients" setting, whatever its called these days.

**Comment by vikaspushkar** [comment]
Why has it started using UDP sockets instead of TCP socket? if yes then Why such a changes has been introduced and since when it is introduced?
