### ISSUE TITLE
CoRD Insecure Update Mechanism

### ISSUE THREAD

**Issue by iallison** [dorianj/CoRD#80]
It appears that CoRD uses an insecure update mechanism. 
In the CoRD /Applications/CoRD.app/Contents/Info.plist file the SUFeedURL is set to:
<string>http://cord.sourceforge.net/sparkle.xml</string>

This setting makes your application vulnerable to a Man-in-the-middle attack application updates.

Please update the SUFeedURL string to use https instead of http to mitigate this issue.

**Comment by peelman** [comment]
CoRD is deprecated and we encourage the move to other clients:

https://github.com/dorianj/CoRD/blob/master/README.md
